version: '3.4'

services:
  hackamed:
    image: ${DOCKER_REGISTRY-}hackamed
    build:
      context: .
      dockerfile: HackaMed/Dockerfile
    ports:
      - "7007:80"
      - "7008:443"
    networks:
      - prod-network
    environment:
      DatabaseConfig__ConnectionString: 'mongodb://admin:abc123!@mongodb-hackamed:27017'
      DatabaseConfig__DatabaseName: 'hackamed'
      DatabaseConfig__User: 'admin'
      DatabaseConfig__Password: 'abc123!'
      AWS_ACCESS_KEY_ID: ''
      AWS_SECRET_ACCESS_KEY: ''
      AWS_REGION: 'us-east-1'
      MY_SECRET: ''
    depends_on:
      - mongodb
 

  mongodb:
    image: mongo:latest
    networks:
      - prod-network
    container_name: mongodb-hackamed
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'abc123!'

networks:
  prod-network:
    driver: bridge