---
apiVersion: v1
kind: Service
metadata:
  name: public-lb-hackamed
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: hackamed
  ports:
    - protocol: TCP
      port: 80
