
name: .NET

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.200

    - name: Restore dependencies
      run: dotnet restore ./src/HackaMed/HackaMed.sln

    - name: Build
      run: dotnet build ./src/HackaMed/HackaMed.sln --no-restore

    #- name: Tests
     # run: dotnet test ./src/HackaMed/HackaMed.sln

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Docker Login
      run: aws ecr get-login-password --region ${{secrets.AWS_REGION}} | docker login --username AWS --password-stdin ${{ secrets.AWS_REGISTRY_URL }}

    - name: Build and Push Docker images
      run: |
        cd src
        cd techchallenge-microservico-pagamento
        docker build -t hackamed-img:latest -f HackaMed/Dockerfile .
        docker tag hackamed-img:latest ${{ secrets.AWS_REGISTRY_URL }}:hackamed-img
        docker push ${{ secrets.AWS_REGISTRY_URL }}:hackamed-img

        docker tag hackamed-img:latest ${{ secrets.DOCKER_HUB_URL }}:hackamed-img
        docker push ${{ secrets.DOCKER_HUB_URL }}:hackamed-img


      # - name: Deploy to EKS
     #   run: |
     #    cd src
     #   cd HackaMed
      #   aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}
      #   kubectl apply -f ./k8s/
